version: '3.4'


services:
  dotcms-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: dotcms-jenkins
    environment:
      - JENKINS_OPTS="--httpPort=8085"
      - JAVA_OPTS="-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=120"
    volumes:
      - ./jenkinsData:/var/jenkins_home
    ports:
      - 8085:8085
      - 50000:50000